Create 2-Quick-sort.md
Abishethvarman/programming-resources pull request #101
Opened 2023-10-20 14:35 UTC by Mohitraut07

Issue: #59
issue solved and quick sort algo

2023-10-20 14:39 UTC, Abishethvarman commented
@Mohitraut07 chnage the PR title in the correct format. Refer previous merged PR

2023-10-21 12:55 UTC, Abishethvarman commented
> Issue: #59 issue solved and quick sort algo

Add proper description by mentioning what algorithm and what language

2023-10-21 17:52 UTC, Mohitraut07 commented
@Abishethvarman please check and review the PR.

2023-10-22 06:38 UTC, Abishethvarman requested changes

2023-10-22 06:38 UTC, Abishethvarman commented on 2-algorithms/2-javascript/2-Quick-sort.md
> +Certainly! Here's a README file for the Quick Sort algorithm in JavaScript:
What about this line

2023-10-22 06:39 UTC, Abishethvarman commented on 2-algorithms/2-javascript/2-Quick-sort.md
> +Certainly! Here's a README file for the Quick Sort algorithm in JavaScript:
remove the line and resolve the issues

2023-10-22 08:10 UTC, Mohitraut07 commented on 2-algorithms/2-javascript/2-Quick-sort.md
> +Certainly! Here's a README file for the Quick Sort algorithm in JavaScript:
okay

2023-10-22 08:11 UTC, Mohitraut07 commented on 2-algorithms/2-javascript/2-Quick-sort.md
> +Certainly! Here's a README file for the Quick Sort algorithm in JavaScript:
will remove it ASAP.

2023-10-22 08:28 UTC, Abishethvarman reviewed
ok

2023-10-22 08:29 UTC, Abishethvarman approved these changes
Approved to merge

2023-10-22 16:29 UTC, Thevapriyan07 approved these changes
Approve to merge

2023-10-22 16:29 UTC, merged