Added Bubble Sort Algorithm in JavaScript
Abishethvarman/programming-resources pull request #118
Opened 2023-10-24 10:21 UTC by sakshipatil4403

Description:
This pull request introduces the Bubble Sort algorithm implemented in JavaScript, along with a comprehensive README file.

Changes Made:
Added JavaScript code for the Bubble Sort algorithm.
Included a README file with the following sections:
Definition: Describes the algorithm's purpose and operation.
Explanation in Simple Terms: Provides a non-technical explanation for easy understanding.
Code-Related Explanation: Offers a detailed breakdown of the JavaScript code.
Included example usage and a sample array for sorting.

Purpose:
The purpose of this contribution is to provide developers with a clear and educational resource for understanding and implementing the Bubble Sort algorithm in JavaScript. The README file ensures that both technical and non-technical users can grasp the concept and its practical application.

 @Abishethvarman    Please review this PR, and if it aligns with the project's goals, consider merging it. Your feedback and suggestions are welcome. Thank you!

2023-10-24 17:25 UTC, Abishethvarman requested changes

2023-10-24 17:25 UTC, Abishethvarman commented on Bubble-Sort_Javascript/Bubble-Sort.js
> +function bubbleSort(arr) {
add this code file in the readme file and make a compact one

2023-10-25 10:17 UTC, sakshipatil4403 commented
Hello @Abishethvarman i made changes in the Readme file

2023-10-25 11:01 UTC, Abishethvarman requested changes

2023-10-25 11:01 UTC, Abishethvarman commented on Bubble-Sort_Javascript/README.md
> +Definition
make a h1 heading "Bubble sort in JavaScript"

2023-10-25 11:01 UTC, Abishethvarman commented on Bubble-Sort_Javascript/README.md
check the file location. file should be in 2-algorithm/2-javacript/and-your-file

2023-10-27 12:27 UTC, sakshipatil4403 commented
Hello @Abishethvarman I kindly request that you review my pull request and, if you find it suitable, consider merging it with the "hacktoberfest-accepted" label. This will not only help me in achieving my Hacktoberfest goals but will also contribute to the growth and development of the project.

2023-10-27 17:09 UTC, Abishethvarman approved these changes
Approved to merge

2023-10-27 17:13 UTC, Abishethvarman commented
@Thevapriyan07 please review this PR ASAP and merge it.

2023-10-29 06:59 UTC, Thevapriyan07 approved these changes
Approve to merge

2023-10-29 06:59 UTC, merged