Added shellsort in python
Abishethvarman/programming-resources pull request #122
Opened 2023-10-27 15:50 UTC by Vybhavigithub

Shellsort algorithm in python is placed in Algorithm-python folder.

2023-10-27 16:54 UTC, Abishethvarman requested changes

2023-10-27 16:54 UTC, Abishethvarman commented on 2-algorithms/3-python/Shellsort.MD
> +"""
Add h1 heading

2023-10-27 17:03 UTC, Vybhavigithub commented
@Abishethvarman please do review

2023-10-27 17:05 UTC, Abishethvarman requested changes

2023-10-27 17:05 UTC, Abishethvarman commented on 2-algorithms/3-python/Shellsort.MD
> +"""
your content seems good, but we need the definition, simple explantion and the code level explanation. please refer this MD file and make changes accordingly https://github.com/Abishethvarman/programming-resources/blob/main/2-algorithms/1-java/merge-sort.MD

2023-10-27 17:17 UTC, Vybhavigithub commented
@Abishethvarman I've made changes accordingly . Please do check.

2023-10-27 17:40 UTC, Abishethvarman requested changes

2023-10-27 17:40 UTC, Abishethvarman commented on 2-algorithms/3-python/Shellsort.py
no py file needed. one single md file is enough

2023-10-27 17:44 UTC, Vybhavigithub commented on 2-algorithms/3-python/Shellsort.py
okay

2023-10-27 17:46 UTC, Abishethvarman approved these changes
Approved to merge

2023-10-27 17:47 UTC, Abishethvarman commented
@Thevapriyan07 approve this PR

2023-10-29 06:43 UTC, Thevapriyan07 approved these changes
Approve to merge

2023-10-29 06:43 UTC, merged