7-bubble sort
Abishethvarman/programming-resources pull request #65
Opened 2023-10-16 18:08 UTC by Sanchayan12

This is PR for bubble sort in java

2023-10-17 12:23 UTC, Sanchayan12 commented on 1-data-structures/1-java/7-bubble sort
I have already change the name

2023-10-17 13:25 UTC, Abishethvarman commented
Rename the title of the PR like "PR: Algo <algorithm name> in <programming language >"

2023-10-17 13:26 UTC, Sanchayan12 commented
I have made the changes

2023-10-17 17:30 UTC, Thevapriyan07 approved these changes

2023-10-17 17:31 UTC, Abishethvarman approved these changes
Approved

2023-10-17 18:26 UTC, Abishethvarman requested changes
"1-data-structures/1-java/7-bubble sort" this path should be "2-algorithm/1-java/7-bubble-sort.MD"

2023-10-18 12:26 UTC, Abishethvarman requested changes
You placed your file in data structure. Replace it in the Algorithm folder

2023-10-18 12:27 UTC, Abishethvarman commented
Better close this PR and create a new

2023-10-18 12:32 UTC, closed without merging

2023-10-18 12:48 UTC, Abishethvarman commented
closed due to relocation issue