4-quicksort.MD
Abishethvarman/programming-resources pull request #66
Opened 2023-10-16 18:17 UTC by vimalvijenthiran

This is a PR for quick sort issue in python

2023-10-17 06:46 UTC, Abishethvarman approved these changes
Approved to merge

2023-10-17 12:24 UTC, Thevapriyan07 commented on 1-data-structures/3-python/4-quicksort.MD
> +QuickSort is a popular sorting algorithm that follows the divide-and-conquer paradigm. It works by selecting a 'pivot' element from the array and partitioning the other elements into two sub-arrays a
make this readme file with #Definition and add some other thing which are  mentioned in the issue
using proper way to write readme file

2023-10-17 13:28 UTC, Abishethvarman requested changes

2023-10-17 13:28 UTC, Abishethvarman commented on 1-data-structures/3-python/4-quicksort.MD
> +QuickSort is a popular sorting algorithm that follows the divide-and-conquer paradigm. It works by selecting a 'pivot' element from the array and partitioning the other elements into two sub-arrays a
Add heading

2023-10-18 12:41 UTC, closed without merging

2023-10-18 12:47 UTC, Abishethvarman commented
closed due to file relocation issue